#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Zero.Droid.Resource", IsApplication=true)]

namespace Zero.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.1.0.5")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int cardProd1 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int cardProd10 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int cardProd11 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int cardProd12 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int cardProd2 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int cardProd3 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int cardProd4 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int cardProd5 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int cardProd6 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int cardProd7 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int cardProd8 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int cardProd9 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int gato = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
